export const BASE_URL="http://localhost:3000/"
export const BACKEND_URL="http://localhost:4000/"
export const BOOKING_URL="api/booking"
export const FAKEBOOKING_URL="api/fakebooking"
export const TRAVELPLAN_URL="api/travelplan"
export const GETPRICE_URL="api/price"